### PR TITLE
Allow customizing environment

### PR DESCRIPTION
**Pull request by rubdos**
I've had this patch laying around for a long while now. I'm not sure whether it actually does something, but I at least wanted it out somewhere :-)

### CODE REVIEW

**Comment by koute** [comment]
Hmm... I'm somewhat conflicted about this. (:

On one hand it's potentially useful, on the other hand if someone needs to access something through the environment interface I'd prefer they contribute a safe and high level interface for it here. (:

Were you actually using this for something?

**Comment by rubdos** [comment]
Yes! Seems like I wanted to set the logging interface. Maybe it's useful to have the standard Rust `log` interface optionally enabled?

**Comment by koute** [comment]
Yep, a shim which routes everything from Rust's `log` to libretro's logger would be a great addition! (I wouldn't mind having it enabled by default, provided it can be easily disabled.)

**Comment by rubdos** [comment]
> Yep, a shim which routes everything from Rust's `log` to libretro's logger would be a great addition! (I wouldn't mind having it enabled by default, provided it can be easily disabled.)

Currently doing some other work, but when I come back to this I'll certainly contribute the logging interface :-)

**Comment by rubdos** [comment]
I'm quite sure I was using it for something else too, but I'll reopen if that persists. Closing in favour of #15! :tada:

**Pull request closed without merging**
