### PR TITLE
Make call_environment method public.

### PR DESCRIPTION
**Pull request by FlorianUekermann**
Getting access to the libretro environment callback is essential for taking advantage of functionality that is not yet implemented or beyond the scope of libretro-backend. Unless I am missing some other facility for this, either `ENVIRONMENT_CALLBACK` or `call_environment` needs to be public to achieve this. 

I opted for `call_environment`, because it is safer and more convenient. Even with `call_environment` being public, an `unsafe` block like the following is needed, which should be sufficiently discouraging:
```
unsafe {
    let result = (&mut *LIBRETRO_INSTANCE).call_environment(libretro_sys::ENVIRONMENT_XXX, &xxx);
    // check result
}
```

### CODE REVIEW

**Comment by koute** [comment]
The `LIBRETRO_INSTANCE` is an implementation detail and isn't actually meant to be accessible by the users. (I really should have named it so that this fact is more obvious.)

I *guess* we could expose the environment callback, but in such case I'd probably prefer to just export something like this:

```rust
pub fn environment_callback() -> libretro_sys::EnvironmentFn {
    ENVIRONMENT_CALLBACK.unwrap()
}
```

**Comment by FlorianUekermann** [comment]
Keeping `LIBRETRO_INSTANCE` out of the library interface sounds good to me. Come to think of it, maybe it doesn't have to be defined at all... ...but that is a different topic.

I used the method, because it is so much more convenient than retrieving `ENVIRONMENT_CALLBACK`, but that is a matter of implementing the function nicely. So how about moving the whole method out of  `LIBRETRO_INSTANCE` and exposing it like this:
```
#[must_use]
pub unsafe fn call_environment< T >(command: libc::c_uint, pointer: &T ) -> Result< (), () > {
    let ok = ENVIRONMENT_CALLBACK.unwrap()( command, mem::transmute( pointer ) );
    if ok {
        Ok(())
    } else {
        Err(())
    }
}
```
I don't think there is a point in storing the callback as a value another time, introducing state that needs to be initialized in the users code. That seems more like an unavoidable implementation detail of libretro that should be abstracted.

Not sure if the function should be marked unsafe, or the pointer type should be adjusted accordingly.

**Comment by FlorianUekermann** [comment]
I guess there should be a `mut` on the pointer argument, right?

**Comment by FlorianUekermann** [comment]
Closing this. I dropped libretro-backend in favor of using only libretro-sys. For projects using hardware accelerated graphics, libretro-backend isn't a good fit.
Just a macro generating the required C functions and a static struct with libretro data would be great for those usecases. The setter functions could populate the struct, while the others wrap functions with hard coded names that the user has to provide. But that is probably a macro that belongs in libretro-sys, not here.

**Pull request closed without merging**
