### PR TITLE
Support retro_get_memory_{data,size}

### PR DESCRIPTION
**Pull request by agi90**
Hi koute!

First off, thanks for the library! It was a breeze to use and I really like how it is implemented. 

I'm using libretro-backend in my game boy emulator here: https://github.com/agi90/gb-rust/tree/master/gb-rust-libretro. I needed get_memory support so I went ahead and forked your repo and I was wondering if you'd like the change upstream.

Here's an example on how I use the feature: https://github.com/agi90/gb-rust/blob/8ebc917fd81e8ad7912d56ffc67e3703dfeb1e4a/gb-rust-libretro/src/lib.rs#L122-L133

Right now the change breaks older clients because it adds a new method to the Core interface. But I can definitely create a new interface if you'd like to.

I've tried to stay consistent with your style, but please let me know if anything looks off.

Commit description:

This change adds support for get_memory methods that can be used to add native
save, rtc, and ram support to a libretro core.

I've bumped the version because this change adds a new method to the `Core`
interface and thus breaks older clients.  However, it should be pretty easy to
implement an empty version of the `memory_data` method like so:

```
fn memory_data( &mut self, _: MemoryType ) -> Option< &mut [u8] > {
    None
}
```

A `Core` is supposed to return the respective memory area from `memory_data` for
each type of memory it supports. E.g. a `Core` that supports saves should have

```
fn memory_data( &mut self, memory_type: MemoryType ) -> Option< &mut [u8] > {
    match memory_type {
        MemoryType::SaveRam => {
            // return mutable reference to the save ram
        },
        _ => None,
    }
}
```

The libretro documentation describes how each memory type is supposed to be
used.

### CODE REVIEW

**Comment by koute** [comment]
Hi!

Thanks for the PR!

Hmmm... this looks pretty good! But, now that I think about it - maybe it would be better to have a separate function for each memory type? Something like `save_memory`, `rtc_memory`, `system_memory` and `video_memory`? I think it would be more self-documenting (i.e. `memory_data` is kinda vague while `save_memory` says directly what it is on the tin) and in general simpler (no need to match the enum).

What do you think?

And also, since not every emulator will want to implement those and since they're not necessary to the emulator to work we could add defaults for them returning `None` in the trait. That would also make this change backwards compatible.

Also, two other things:
  1. By convention variables in Rust that start with an underscore are unused (which is why the compiler doesn't warn you that they're unused); if we start to use a variable named `_foobar` we should rename it to `foobar`. (:
  2. It's not possible to limit the visibility of an impl, so if you have something like `impl From< libc::c_uint > for Foobar` and `Foobar` is public then everyone will have access to that impl, which is not ideal if the impl itself is supposed to be an implementation detail. (In cases like that it's usually better to simply make a helper function that does the job.)

**Comment by koute** [comment]
Oh and also, love your emulator! It's really nicely written; very clean! Great job!

**Comment by agi90** [comment]
Thanks for the comments! Responses inline.

> Hmmm... this looks pretty good! But, now that I think about it - maybe it would be better to have a separate function for each memory type? Something like save_memory, rtc_memory, system_memory and video_memory? I think it would be more self-documenting (i.e. memory_data is kinda vague while save_memory says directly what it is on the tin) and in general simpler (no need to match the enum).

Yeah, that's a good idea! I've made the change.

> And also, since not every emulator will want to implement those and since they're not necessary to the emulator to work we could add defaults for them returning None in the trait. 

I somehow knew you could set defaults in traits but completely forgot! I added that.

> By convention variables in Rust that start with an underscore are unused (which is why the compiler doesn't warn you that they're unused); if we start to use a variable named _foobar we should rename it to foobar. (:

TIL!

> It's not possible to limit the visibility of an impl, so if you have something like impl From< libc::c_uint > for Foobar and Foobar is public then everyone will have access to that impl, which is not ideal if the impl itself is supposed to be an implementation detail. (In cases like that it's usually better to simply make a helper function that does the job.)

Nice to know! That struct does not exist anymore so the problem is gone.

> Oh and also, love your emulator! It's really nicely written; very clean! Great job!

Thanks! :-)

**Comment by koute** [comment]
Looks good to me! Thanks again!

I'll publish this on crates.io once I get back home.

**Pull request merged**
